# Generated by Django 4.2.6 on 2023-10-14 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treelikemenu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='submenu_name')),
                ('url', models.URLField(verbose_name='menu_url')),
                ('parent_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treelikemenu.menu')),
            ],
        ),
    ]
