# Generated by Django 4.2.6 on 2023-10-14 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treelikemenu', '0002_submenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='parent_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='treelikemenu.menu'),
        ),
        migrations.DeleteModel(
            name='Submenu',
        ),
    ]
