# Generated by Django 4.2.6 on 2023-10-16 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treelikemenu', '0004_alter_menu_parent_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='category_name')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='parent_category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='treelikemenu.categody'),
        ),
    ]
