# Generated by Django 4.2.6 on 2023-10-16 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treelikemenu', '0006_alter_menu_parent_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='parent_category',
        ),
    ]
