# Generated by Django 4.2.6 on 2023-10-16 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treelikemenu', '0008_menu_parent_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categody',
            new_name='Category',
        ),
    ]
